AWSTemplateFormatVersion: '2010-09-09'
Description: Guitar Collection Frontend Infrastructure

Parameters:
  DomainName:
    Type: String
    Description: Domain name for the frontend (e.g., example.com)
    Default: your-domain.com

  BucketPrefix:
    Type: String
    Description: Prefix for the S3 bucket name (e.g., my-app-frontend)
    Default: my-app-frontend

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for your domain (required)

Resources:
  # S3 Bucket for static website hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketPrefix}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      Tags:
        - Key: Environment
          Value: prod

  # Bucket Policy for CloudFront access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontOAI
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${FrontendOAI}'
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'

  # CloudFront Origin Access Identity
  FrontendOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${DomainName}'

  # ACM Certificate for HTTPS
  FrontendCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  # CloudFront Distribution
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CDN for ${DomainName}'
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${FrontendOAI}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref FrontendCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # Route53 DNS Record
  FrontendDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt FrontendDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (constant)
        EvaluateTargetHealth: false

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref FrontendBucket
    Export:
      Name: frontend-bucket-name

  DistributionId:
    Description: CloudFront distribution ID
    Value: !Ref FrontendDistribution
    Export:
      Name: frontend-distribution-id

  DistributionDomain:
    Description: CloudFront distribution domain
    Value: !GetAtt FrontendDistribution.DomainName
    Export:
      Name: frontend-distribution-domain

  WebsiteUrl:
    Description: Website URL
    Value: !Sub 'https://${DomainName}'
    Export:
      Name: frontend-website-url
