import { Guitar, GuitarType } from '../types/guitar';

export const mockGuitars: Guitar[] = [
  {
    id: '1',
    userId: 'mock-user',
    brand: 'Fender',
    model: 'Stratocaster American Professional II',
    year: 2021,
    type: GuitarType.ELECTRIC,
    bodyMaterial: 'Alder',
    neckMaterial: 'Maple',
    fretboardMaterial: 'Rosewood',
    numberOfFrets: 22,
    scaleLength: '25.5"',
    pickupConfiguration: 'SSS (3 Single-Coil)',
    color: 'Miami Blue',
    finish: 'Gloss',
    tuningMachines: 'Fender Deluxe Cast/Sealed',
    bridge: 'Two-Point Synchronized Tremolo',
    nut: 'Bone',
    caseIncluded: true,
    images: [
      {
        id: 'img1',
        url: 'https://via.placeholder.com/800x600/4A90E2/FFFFFF?text=Fender+Strat',
        thumbnailUrl: 'https://via.placeholder.com/300x225/4A90E2/FFFFFF?text=Fender+Strat',
        isPrimary: true,
        order: 1,
      },
    ],
    privateInfo: {
      serialNumber: 'US21045678',
      purchaseDate: '2021-06-15',
      purchasePrice: 1899.99,
      purchaseLocation: 'Sweetwater',
      currentValue: 1800.0,
    },
    notes: [
      {
        id: 'note-1',
        content: 'My go-to guitar for recording. Love the neck profile.',
        createdAt: '2021-06-15T12:00:00Z',
      },
    ],
    createdAt: '2021-06-15T12:00:00Z',
    updatedAt: '2024-01-10T08:30:00Z',
  },
  {
    id: '2',
    userId: 'mock-user',
    brand: 'Gibson',
    model: 'Les Paul Standard 50s',
    year: 2020,
    type: GuitarType.ELECTRIC,
    bodyMaterial: 'Mahogany with Maple Top',
    neckMaterial: 'Mahogany',
    fretboardMaterial: 'Rosewood',
    numberOfFrets: 22,
    scaleLength: '24.75"',
    pickupConfiguration: 'HH (2 Humbuckers)',
    color: 'Heritage Cherry Sunburst',
    finish: 'Gloss Nitrocellulose',
    tuningMachines: 'Grover Rotomatic',
    bridge: 'ABR-1 Tune-O-Matic',
    nut: 'GraphTech',
    electronics: 'Burstbucker 61 (Rhythm) and Burstbucker 61 (Treble)',
    caseIncluded: true,
    images: [
      {
        id: 'img2',
        url: 'https://via.placeholder.com/800x600/8B4513/FFFFFF?text=Gibson+Les+Paul',
        thumbnailUrl: 'https://via.placeholder.com/300x225/8B4513/FFFFFF?text=Gibson+Les+Paul',
        isPrimary: true,
        order: 1,
      },
    ],
    privateInfo: {
      serialNumber: 'GB20125432',
      purchaseDate: '2020-11-20',
      purchasePrice: 2799.0,
      purchaseLocation: 'Guitar Center',
      currentValue: 2600.0,
    },
    notes: [
      {
        id: 'note-2',
        content: 'Perfect for heavy rock tones. The sustain is incredible.',
        createdAt: '2020-11-20T14:00:00Z',
      },
    ],
    createdAt: '2020-11-20T14:00:00Z',
    updatedAt: '2024-01-10T08:30:00Z',
  },
  {
    id: '3',
    userId: 'mock-user',
    brand: 'Martin',
    model: 'D-28',
    year: 2019,
    type: GuitarType.ACOUSTIC,
    bodyMaterial: 'Rosewood Back & Sides, Sitka Spruce Top',
    neckMaterial: 'Select Hardwood',
    fretboardMaterial: 'Ebony',
    numberOfFrets: 20,
    scaleLength: '25.4"',
    pickupConfiguration: 'None',
    color: 'Natural',
    finish: 'Gloss',
    tuningMachines: 'Nickel Open-Gear',
    bridge: 'Ebony Belly',
    nut: 'Bone',
    caseIncluded: true,
    images: [
      {
        id: 'img3',
        url: 'https://via.placeholder.com/800x600/D2691E/FFFFFF?text=Martin+D-28',
        thumbnailUrl: 'https://via.placeholder.com/300x225/D2691E/FFFFFF?text=Martin+D-28',
        isPrimary: true,
        order: 1,
      },
    ],
    privateInfo: {
      serialNumber: 'MT19078912',
      purchaseDate: '2019-08-10',
      purchasePrice: 3199.0,
      purchaseLocation: 'Local Music Shop',
      currentValue: 3000.0,
    },
    notes: [
      {
        id: 'note-3',
        content: 'Classic dreadnought tone. Perfect for fingerpicking and strumming.',
        createdAt: '2019-08-10T10:00:00Z',
      },
    ],
    createdAt: '2019-08-10T10:00:00Z',
    updatedAt: '2024-01-10T08:30:00Z',
  },
  {
    id: '4',
    userId: 'mock-user',
    brand: 'PRS',
    model: 'Custom 24',
    year: 2022,
    type: GuitarType.ELECTRIC,
    bodyMaterial: 'Mahogany with Figured Maple Top',
    neckMaterial: 'Mahogany',
    fretboardMaterial: 'Rosewood',
    numberOfFrets: 24,
    scaleLength: '25"',
    pickupConfiguration: 'HH (85/15 Humbuckers)',
    color: 'Blue Fade',
    finish: 'Gloss',
    tuningMachines: 'PRS Phase III Locking',
    bridge: 'PRS Tremolo',
    nut: 'PRS',
    electronics: '85/15 Treble & Bass Pickups with Volume & Tone Control, 5-Way Blade Switch',
    caseIncluded: true,
    images: [
      {
        id: 'img4',
        url: 'https://via.placeholder.com/800x600/191970/FFFFFF?text=PRS+Custom+24',
        thumbnailUrl: 'https://via.placeholder.com/300x225/191970/FFFFFF?text=PRS+Custom+24',
        isPrimary: true,
        order: 1,
      },
    ],
    privateInfo: {
      serialNumber: 'PRS22305678',
      purchaseDate: '2022-03-25',
      purchasePrice: 4200.0,
      purchaseLocation: 'Online - PRS Direct',
      currentValue: 4000.0,
    },
    notes: [
      {
        id: 'note-4',
        content: 'Incredibly versatile. The best of both Fender and Gibson worlds.',
        createdAt: '2022-03-25T16:00:00Z',
      },
    ],
    createdAt: '2022-03-25T16:00:00Z',
    updatedAt: '2024-01-10T08:30:00Z',
  },
];
