/**
 * Predefined suggestions for guitar specifications
 */

export const GUITAR_SUGGESTIONS = {
  // Main Specifications
  brands: [
    'Fender',
    'Gibson',
    'PRS (Paul Reed Smith)',
    'Ibanez',
    'Martin',
    'Taylor',
    'Gretsch',
    'Epiphone',
    'Squier',
    'Jackson',
    'ESP',
    'Schecter',
    'Yamaha',
    'Takamine',
    'Guild',
    'Rickenbacker',
    'Music Man',
    'Charvel',
    'Kramer',
    'Washburn',
    'Dean',
    'BC Rich',
    'G&L',
    'Suhr',
    'Anderson',
    'Collings',
    'Santa Cruz',
    'Breedlove',
    'Godin',
    'Seagull',
  ],

  bodyMaterials: [
    'Mahogany',
    'Alder',
    'Ash',
    'Maple',
    'Basswood',
    'Poplar',
    'Koa',
    'Walnut',
    'Swamp Ash',
    'Spanish Cedar',
    'Agathis',
    'Nato',
    'Okoume',
    'Sapele',
    'Spruce',
    'Cedar',
    'Rosewood',
  ],

  neckMaterials: [
    'Maple',
    'Mahogany',
    'Roasted Maple',
    'Wenge',
    'Walnut',
    'Nato',
    'Bubinga',
    'Maple with Walnut Stripe',
    'Maple with Rosewood Stripe',
    '3-Piece Maple',
    '5-Piece Maple/Walnut',
  ],

  fretboardMaterials: [
    'Rosewood',
    'Maple',
    'Ebony',
    'Pau Ferro',
    'Richlite',
    'Laurel',
    'Baked Maple',
    'Ovangkol',
    'Katalox',
    'Ziricote',
  ],

  pickupConfigurations: [
    'SSS (3 Single Coils)',
    'HH (2 Humbuckers)',
    'HSS (Humbucker/Single/Single)',
    'HSH (Humbucker/Single/Humbucker)',
    'H (Single Humbucker)',
    'HHH (3 Humbuckers)',
    'SS (2 Single Coils)',
    'P90/P90',
    'P90/Humbucker',
    'S/Humbucker',
  ],

  colors: [
    '3-Tone Sunburst',
    '2-Tone Sunburst',
    'Vintage Sunburst',
    'Tobacco Burst',
    'Cherry Burst',
    'Black',
    'White',
    'Olympic White',
    'Arctic White',
    'Natural',
    'Honey Burst',
    'Transparent Red',
    'Transparent Blue',
    'Transparent Black',
    'Seafoam Green',
    'Surf Green',
    'Daphne Blue',
    'Lake Placid Blue',
    'Sonic Blue',
    'Shell Pink',
    'Burgundy Mist',
    'Fiesta Red',
    'Candy Apple Red',
    'Vintage White',
    'Butterscotch',
    'Purple Burst',
    'Ocean Blue',
    'Amber',
  ],

  finishes: [
    'Gloss Polyurethane',
    'Gloss Polyester',
    'Gloss Nitrocellulose',
    'Satin Polyurethane',
    'Satin Nitrocellulose',
    'Matte',
    'Oil Finish',
    'Tung Oil',
    'Hand-Rubbed Oil',
    'Vintage Nitrocellulose',
    'Thin Skin Nitrocellulose',
    'Open Pore',
  ],

  bridges: [
    'Tune-o-matic',
    'Floyd Rose',
    'Floyd Rose Original',
    'Floyd Rose Special',
    'Vintage Tremolo',
    'Synchronized Tremolo',
    '2-Point Tremolo',
    '6-Point Tremolo',
    'Bigsby B5',
    'Bigsby B7',
    'Hardtail',
    'String-Through Body',
    'Wraparound',
    'PRS Tremolo',
    'Wilkinson Tremolo',
    'Kahler Tremolo',
    'Hipshot',
  ],

  nuts: [
    'Bone',
    'Synthetic Bone',
    'Tusq',
    'Graph Tech',
    'Graphite',
    'Brass',
    'Plastic',
    'Floyd Rose Locking Nut',
    'LSR Roller Nut',
  ],

  tuningMachines: [
    'Grover',
    'Schaller',
    'Gotoh',
    'Hipshot',
    'Kluson',
    'Sperzel Locking',
    'Planet Waves Auto-Trim',
    'Fender Standard',
    'Vintage Style',
    '18:1 Ratio',
    '16:1 Ratio',
    'Locking Tuners',
  ],

  countriesOfOrigin: [
    'USA',
    'Japan',
    'Mexico',
    'China',
    'Korea',
    'South Korea',
    'Indonesia',
    'Taiwan',
    'Germany',
    'United Kingdom',
    'Canada',
    'Spain',
    'Czech Republic',
  ],

  // Detailed Specs
  bodyShapes: [
    'Stratocaster',
    'Telecaster',
    'Les Paul',
    'SG',
    'ES-335',
    'Jazzmaster',
    'Jaguar',
    'Mustang',
    'PRS Custom',
    'Superstrat',
    'Dreadnought',
    'Grand Auditorium',
    'Concert',
    'Parlor',
    'Jumbo',
    'OM (Orchestra Model)',
    'Double Cutaway',
    'Single Cutaway',
    'Offset',
  ],

  neckProfiles: [
    'C-Shape',
    'Modern C',
    'Soft V',
    'V-Shape',
    'U-Shape',
    'D-Shape',
    'Oval',
    'Asymmetrical',
    'Compound Radius',
    'Slim Taper',
    'Wide Fat',
    'Wide Thin',
    'Pattern',
    'Pattern Thin',
    'Pattern Regular',
    'Vintage',
    '59 Roundback',
    'Wizard',
    'Super Wizard',
  ],

  neckJoints: [
    'Set-Neck',
    'Bolt-On',
    'Neck-Through',
    'Set-In',
    '4-Bolt',
    '3-Bolt',
    'Mortise and Tenon',
  ],

  neckFinishes: [
    'Gloss Polyurethane',
    'Satin Polyurethane',
    'Gloss Nitrocellulose',
    'Satin Nitrocellulose',
    'Tung Oil',
    'Gunstock Oil',
    'Satin',
    'Hand-Rubbed',
    'Raw',
    'Unfinished',
  ],

  fretSizes: [
    'Vintage',
    'Medium',
    'Medium Jumbo',
    'Jumbo',
    'Extra Jumbo',
    'Narrow Tall',
    '6105',
    '6100',
    '6130',
    '6150',
    'Stainless Steel',
    'Nickel Silver',
  ],

  fretboardInlays: [
    'Dot',
    'Block',
    'Trapezoid',
    'Split Block',
    'Parallelogram',
    'Birds',
    'Moon',
    'Crown',
    'Abalone Dot',
    'Mother of Pearl',
    'Acrylic',
    'None',
    'Side Dots Only',
  ],

  hardwareFinishes: [
    'Chrome',
    'Gold',
    'Black',
    'Nickel',
    'Aged Nickel',
    'Satin Chrome',
    'Brushed Chrome',
    'Cosmo Black',
    'Oil Rubbed Bronze',
  ],

  pickguards: [
    'White',
    'Black',
    'Tortoise Shell',
    'Mint Green',
    'Cream',
    'Pearl',
    'Pearloid',
    'Black Pearl',
    '3-Ply White',
    '3-Ply Black',
    '1-Ply White',
    '1-Ply Black',
    'None',
  ],

  stringGauges: [
    '.009-.042',
    '.010-.046',
    '.010-.052',
    '.011-.049',
    '.011-.052',
    '.012-.052',
    '.012-.054',
    '.013-.056',
    '.045-.105 (Bass)',
    '.040-.100 (Bass)',
  ],
};
