.PHONY: build-AuthHandler build-GuitarsHandler build-ImagesHandler build-UserHandler build-SpecsHandler build-ReceiptHandler build-PublicGuitarHandler build-DocumentsHandler build-ProvenanceHandler build-DocumentExtractionHandler

build-AuthHandler build-GuitarsHandler build-ImagesHandler build-UserHandler build-SpecsHandler build-ReceiptHandler build-PublicGuitarHandler build-DocumentsHandler build-ProvenanceHandler build-DocumentExtractionHandler:
	echo "Dependencies already installed, skipping npm install"
	cp -r . $(ARTIFACTS_DIR)/
