.PHONY: build-AuthHandler build-GuitarsHandler build-ImagesHandler build-UserHandler build-SpecsHandler build-PublicGuitarHandler build-DocumentsHandler build-ProvenanceHandler

build-AuthHandler build-GuitarsHandler build-ImagesHandler build-UserHandler build-SpecsHandler build-PublicGuitarHandler build-DocumentsHandler build-ProvenanceHandler:
	echo "Dependencies already installed, skipping npm install"
	cp -r . $(ARTIFACTS_DIR)/
